# numpy

In [2]:
import numpy as np
array_1d=np.array([2,5,86,34])
print(array_1d)
print(type(array_1d))

[ 2  5 86 34]
<class 'numpy.ndarray'>


In [3]:
array_2d=np.array([[2,5,86,34],[22,10,30,7]])
print(array_2d)

[[ 2  5 86 34]
 [22 10 30  7]]


In [4]:
li=[5,6,7]
array=np.array(li)
print(array)

[5 6 7]


In [5]:
array2=np.arange(30)
array2.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [6]:
array2[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
array3=np.arange(30)
arr=array3.reshape(6,5)

In [8]:
arr[0,2]

2

In [9]:
array2+array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [11]:
array2*array3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [12]:
array2.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [14]:
array2+10
array2.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [20]:
array4=np.arange(20).reshape(4,5)
array4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
array4+20

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [23]:
print(np.sin(array4))

[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [24]:
print(np.cos(array4))

[[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
 [-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722]
 [-0.75968791 -0.95765948 -0.27516334  0.66031671  0.98870462]]


In [25]:
print(np.log(array4))

[[      -inf 0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334 2.89037176 2.94443898]]


C:\Users\aliet\Anaconda30\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [26]:
print(np.sqrt(array4))

[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]
 [3.87298335 4.         4.12310563 4.24264069 4.35889894]]


In [27]:
print(np.tan(array4))

[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01
   1.15782128e+00]
 [-3.38051501e+00 -2.91006191e-01  8.71447983e-01 -6.79971146e+00
  -4.52315659e-01]
 [ 6.48360827e-01 -2.25950846e+02 -6.35859929e-01  4.63021133e-01
   7.24460662e+00]
 [-8.55993401e-01  3.00632242e-01  3.49391565e+00 -1.13731371e+00
   1.51589471e-01]]


In [31]:
array5=np.arange(30).reshape(5,6)
array5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
array5+5

array([[ 5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [36]:

a=np.sqrt(array5)
print(a)

[[0.         1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563]
 [4.24264069 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152]
 [4.89897949 5.         5.09901951 5.19615242 5.29150262 5.38516481]]


In [37]:
print(np.sin(a))

[[ 0.          0.84147098  0.98776595  0.98702664  0.90929743  0.78674913]
 [ 0.63815764  0.47577184  0.30807174  0.14112001 -0.02068353 -0.17413978]
 [-0.31694716 -0.44749175 -0.5646959  -0.6679053  -0.7568025  -0.83133918]
 [-0.89168225 -0.93817027 -0.9712778  -0.99158608 -0.9997586  -0.99652069]
 [-0.98264244 -0.95892427 -0.92618484 -0.88525077 -0.83694807 -0.7820949 ]]


In [38]:
print(np.cos(a))

[[ 1.          0.54030231  0.15594369 -0.16055654 -0.41614684 -0.61727288]
 [-0.76990573 -0.87956873 -0.95136313 -0.9899925  -0.99978607 -0.98472094]
 [-0.9484432  -0.89428806 -0.82529906 -0.74424627 -0.65364362 -0.55576539]
 [-0.45266186 -0.34617416 -0.23794839 -0.129449   -0.02197145  0.08334575]
 [ 0.18550967  0.28366219  0.37706981  0.46511405  0.54728232  0.62315934]]


In [39]:
print(np.log(a))

[[      -inf 0.         0.34657359 0.54930614 0.69314718 0.80471896]
 [0.89587973 0.97295507 1.03972077 1.09861229 1.15129255 1.19894764]
 [1.24245332 1.28247468 1.31952866 1.3540251  1.38629436 1.41660667]
 [1.44518588 1.47221949 1.49786614 1.52226122 1.54552123 1.56774711]
 [1.58902692 1.60943791 1.62904827 1.64791843 1.66610226 1.68364791]]


C:\Users\aliet\Anaconda30\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [40]:
array6=np.ones((4,5))
array6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
array6=np.ones((4,5))

In [52]:
def primenumber(n):
    count=0
    for i in range(1,n+1):
        if n%i==0:
            count+=1
    if count==2:    
            return True
primenumber(7)            

True

In [59]:
def secondlargest(li):
    unique=[]
    for n in li:
        if n not in unique:
            unique.append(n)
    unique=sorted(unique,reverse=True)
    if len(unique)>1:
        return unique[1]
    #here we want second largest so 2-1=1
    #to find any k th largest take k-1
    return -1
secondlargest([1,2,8,15])

8

In [63]:
def kLargest(li,k):
    unique=[]
    for n in li:
        if n not in unique:
            unique.append(n)
    unique=sorted(unique,reverse=True)
    if len(unique)>=k:
        return unique[k-1]
    return -1
kLargest([2,8,5,4,14],1)

14

In [68]:
def highestFrequencyElement(li):
    unique={}
    for n in li:
        if n in unique:
            unique[n]+=1
        else:
            unique[n]=1
    maxfreq=max(unique.values())
    maxfreqkeys=[]
    for item in unique.items():
        if item[1] == maxfreq:
            maxfreqkeys.append(item[0])
    return min(maxfreqkeys)
highestFrequencyElement([1,8,5,3,2,1,8,3,6])

1

In [ ]:
#function to identify second highest frequency element
#if there are many such elements,return the smallest
#[1,2,3,2,1,4,4,9]

In [93]:
n=input().split()
print(n)

1 2 3 6 5 4
['1', '2', '3', '6', '5', '4']


In [70]:
def secondFrequencyElement(li):
    unique={}
    for n in li:
        if n in unique:
            unique[n]+=1
        else:
            unique[n]=1
    maxfreq=max(unique.values())
    maxfreqkeys=[]
    for item in unique.items():
        if item[1] == maxfreq:
            maxfreqkeys.append(item[1])
    return min(maxfreqkeys)
secondFrequencyElement([1,8,5,3,2,1,8,3,6])

2

In [79]:
#problem:special number
#A spl number is a number which has atleast p-distinct prime numbers
#write a prog to determine whether a number is spl num or not
#i/p:  p second line: T (num of test cases) next T lines:N
#o/p: for each test case print yes or no depending on the result
    
N=int(input())
def prime(n):
    count=0
    for i in range(1,n+1):
        if n%i==0:
            count+=1
    if count==2:    
            return True
def primesin(N):
    for j in range(1,N+1):
        if prime(j):
            print(j,end=" ")
primesin(N)

45
2 3 5 7 11 13 17 19 23 29 31 37 41 43 

In [89]:
N=int(input())
def isprime(n):
    count=0
    for i in range(1,n+1):
        if n%i==0:
            count+=1
    if count==2:    
            return True
def primesin(N):
    for j in range(1,N+1):
        if prime(j):
            print(j,end=" ")
primesin(N)            

8
2 3 5 7 

In [91]:

def splnumber(n,p):
    if numberOfPrimeFactors(n)>=p:
        return True
    return False
def isprime(n):
    flag=1
    if n==2:
        return True
    for i in range(2, n//2+1):
        if n%i==0:
            flag=0
            return False
    if flag==1:
        return True
#function to determin eprime factors for a given number    
def numberOfPrimeFactors(n):
    if isprime(n):
        return 1
    count=0
    for i in range(2,n//2+1):
        if isprime(i) and n%i==0:
            count+=1
    return count
def solution2():
    p=int(input())
    t=int(input())
    for i in range(0,t):
        n=int(input())
        if splnumber(n,p):
            print("YES")
        else:
            print("NO")   
splnumber(30,2)    
        

True